import Head from 'next/head';
import ErrorPageMain from '../components/ErrorPage/ErrorPageMain';
import Footer from '../components/Layout/Footer/FooterOne/Footer';
import HeaderFour from '../components/Layout/Header/HeaderFour/HeaderFour';


export default function ErrorPage() {

  return (
    <>
      <Head>
        <title>Saint John Ambulance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderFour />
      <ErrorPageMain />
      <Footer />
    </>
  )
}
