import Head from 'next/head';
import Footer from '../components/Layout/Footer/FooterOne/Footer';
import HeaderTwo from '../components/Layout/Header/HeaderTwo/HeaderTwo';
import ShopMain from '../components/Shop/ShopMain';


export default function Shop() {

  return (
    <>
      <Head>
        <title>St. John Ambulance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderTwo />
      <ShopMain />
      <Footer />
    </>
  )
}
